#!/bin/bash
##
#SBATCH --job-name=Gauss-Legendre_integration_part1
#SBATCH --output=part1.txt
#SBATCH --output=part1.txt
#SBATCH --partition=compute1
#SBATCH --time=00:20:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=rakib.hasan@utsa.edu
#SBATCH --ntasks=21
#SBATCH --nodes=1

# Load one of these
module load anaconda3
conda activate hpc
conda install -c conda-forge mpi4py mpich
#module load mpich
mpirun -n $SLURM_NTASKS python3 part1.py 
